# Generated by Django 3.2.8 on 2022-05-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('tematica_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.tematica')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.pregunta')),
                ('respuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.respuesta')),
            ],
        ),
    ]
